### ISSUE TITLE
Popp 123610 68g: receive message 'Er is geen geschikt Homey App gevonden voor dit apparaat...'

### ISSUE THREAD

**Issue by dutch66** [mruiter/com.popp#10]
' Er is geen geschikt Homey App gevonden voor dit apparaat. Het apparaat is toegevoegd als Basic-Z-Wate Apparaat'.

Below the device info:
Device: Popp 123610 68g

Fabrikant ID: 340
Product Type ID: 4352
Product ID: 1

Version installed: v1.1.7

**Comment by mruiter** [comment]
Ive added the id's to the beta version of the app on my github
