### ISSUE TITLE
009204 - KFOB-C Remote Control - problems

### ISSUE THREAD

**Issue by xeor** [mruiter/com.popp#11]
I got a kfob-c identical, which have been a little hard to add to my homey.
Using the popp app, I finally got it added, but after the inclusion, it says that it is not able to recognise it in any apps, so it added it as a generic zwave device.

I am looking at https://github.com/mruiter/com.popp/blob/master/app.json#L1534-L1536, and it doesnt match what it got added as:

```
Node ID: 13
Secure: No
Battery: Yes
Manufacturer ID: 277
Product Type ID: 256
Product ID: 2
Device Class (Basic): BASIC_TYPE_ROUTING_SLAVE
Device Class (Generic): GENERIC_TYPE_SWITCH_REMOTE
Device Class (Specific): SPECIFIC_TYPE_SWITCH_REMOTE_MULTILEVEL
```

Any idea what it can be? Is it a faulty device? Bug in the driver? Old firmware?

**Comment by mruiter** [comment]
This seems to be a keyfob from another brand, not POP.
I added these id's to the beta version off the app.

The hard adding is caused by the buggy z-wave implementation of homey
