### ISSUE TITLE
012501 - Strike Lock Control - Notification don't working

### ISSUE THREAD

**Issue by bumer0** [mruiter/com.popp#12]
Hello
012501 - Strike Lock Control
on/off is working correct 

but on the bord has (IN) External Dry Contact on/off 
(Notification Type 0x06 with events open=0x16 and closed=0x17)
and this Notification don't working
could you check?

manual
http://www.vesternet.com/downloads/dl/file/id/1749/product/2635/z_wave_popp_electronic_door_opener_controlmodule_manual.pdf

**Comment by mruiter** [comment]
Please send me the log when app rubs in debug mode with athom project —run

Verstuurd vanaf mijn iPhone

**Comment by bumer0** [comment]
Hello
I am sorry  I am not expert 
could you explain  who to see log after athom project —run

look at picture



_________________
Kostylev Alexander 
+7 926 001 7069
2124187@gmail.com

**Comment by bumer0** [comment]
after that, nothing happens in the terminal
The device removed added including turned off
nothing in the terminal

just what's on the picture

**Comment by bumer0** [comment]
Found a solution to enable the debug mode

Log: 

[debug] ------------------------------------------
[debug] Node: 20a5b29c-91fe-412a-94ce-551b27ae79e9
[debug] - Battery: false
[debug] - CommandClass: COMMAND_CLASS_ZWAVEPLUS_INFO
[debug] -- Version: 2
[debug] -- Commands:
[debug] --- ZWAVEPLUS_INFO_GET
[debug] --- ZWAVEPLUS_INFO_REPORT
[debug] - CommandClass: COMMAND_CLASS_SENSOR_BINARY
[debug] -- Version: 2
[debug] -- Commands:
[debug] --- SENSOR_BINARY_GET
[debug] --- SENSOR_BINARY_REPORT
[debug] --- SENSOR_BINARY_SUPPORTED_GET_SENSOR
[debug] --- SENSOR_BINARY_SUPPORTED_SENSOR_REPORT
[debug] - CommandClass: COMMAND_CLASS_NOTIFICATION
[debug] -- Version: 5
[debug] -- Commands:
[debug] --- NOTIFICATION_GET
[debug] --- NOTIFICATION_REPORT
[debug] --- NOTIFICATION_SET
[debug] --- NOTIFICATION_SUPPORTED_GET
[debug] --- NOTIFICATION_SUPPORTED_REPORT
[debug] --- EVENT_SUPPORTED_GET
[debug] --- EVENT_SUPPORTED_REPORT
[debug] - CommandClass: COMMAND_CLASS_CONFIGURATION
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- CONFIGURATION_GET
[debug] --- CONFIGURATION_REPORT
[debug] --- CONFIGURATION_SET
[debug] - CommandClass: COMMAND_CLASS_ASSOCIATION
[debug] -- Version: 2
[debug] -- Commands:
[debug] --- ASSOCIATION_GET
[debug] --- ASSOCIATION_GROUPINGS_GET
[debug] --- ASSOCIATION_GROUPINGS_REPORT
[debug] --- ASSOCIATION_REMOVE
[debug] --- ASSOCIATION_REPORT
[debug] --- ASSOCIATION_SET
[debug] --- ASSOCIATION_SPECIFIC_GROUP_GET
[debug] --- ASSOCIATION_SPECIFIC_GROUP_REPORT
[debug] - CommandClass: COMMAND_CLASS_BATTERY
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- BATTERY_GET
[debug] --- BATTERY_REPORT
[debug] - CommandClass: COMMAND_CLASS_FIRMWARE_UPDATE_MD
[debug] -- Version: 3
[debug] -- Commands:
[debug] --- FIRMWARE_MD_GET
[debug] --- FIRMWARE_MD_REPORT
[debug] --- FIRMWARE_UPDATE_MD_GET
[debug] --- FIRMWARE_UPDATE_MD_REPORT
[debug] --- FIRMWARE_UPDATE_MD_REQUEST_GET
[debug] --- FIRMWARE_UPDATE_MD_REQUEST_REPORT
[debug] --- FIRMWARE_UPDATE_MD_STATUS_REPORT
[debug] - CommandClass: COMMAND_CLASS_DEVICE_RESET_LOCALLY
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- DEVICE_RESET_LOCALLY_NOTIFICATION
[debug] - CommandClass: COMMAND_CLASS_ASSOCIATION_GRP_INFO
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- ASSOCIATION_GROUP_NAME_GET
[debug] --- ASSOCIATION_GROUP_NAME_REPORT
[debug] --- ASSOCIATION_GROUP_INFO_GET
[debug] --- ASSOCIATION_GROUP_INFO_REPORT
[debug] --- ASSOCIATION_GROUP_COMMAND_LIST_GET
[debug] --- ASSOCIATION_GROUP_COMMAND_LIST_REPORT
[debug] - CommandClass: COMMAND_CLASS_POWERLEVEL
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- POWERLEVEL_GET
[debug] --- POWERLEVEL_REPORT
[debug] --- POWERLEVEL_SET
[debug] --- POWERLEVEL_TEST_NODE_GET
[debug] --- POWERLEVEL_TEST_NODE_REPORT
[debug] --- POWERLEVEL_TEST_NODE_SET
[debug] - CommandClass: COMMAND_CLASS_SECURITY
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- NETWORK_KEY_SET
[debug] --- NETWORK_KEY_VERIFY
[debug] --- SECURITY_COMMANDS_SUPPORTED_GET
[debug] --- SECURITY_COMMANDS_SUPPORTED_REPORT
[debug] --- SECURITY_MESSAGE_ENCAPSULATION
[debug] --- SECURITY_MESSAGE_ENCAPSULATION_NONCE_GET
[debug] --- SECURITY_NONCE_GET
[debug] --- SECURITY_NONCE_REPORT
[debug] --- SECURITY_SCHEME_GET
[debug] --- SECURITY_SCHEME_INHERIT
[debug] --- SECURITY_SCHEME_REPORT
[debug] - CommandClass: COMMAND_CLASS_DOOR_LOCK
[debug] -- Version: 2
[debug] -- Commands:
[debug] --- DOOR_LOCK_CONFIGURATION_GET
[debug] --- DOOR_LOCK_CONFIGURATION_REPORT
[debug] --- DOOR_LOCK_CONFIGURATION_SET
[debug] --- DOOR_LOCK_OPERATION_GET
[debug] --- DOOR_LOCK_OPERATION_REPORT
[debug] --- DOOR_LOCK_OPERATION_SET
[debug] - CommandClass: COMMAND_CLASS_VERSION
[debug] -- Version: 2
[debug] -- Commands:
[debug] --- VERSION_COMMAND_CLASS_GET
[debug] --- VERSION_COMMAND_CLASS_REPORT
[debug] --- VERSION_GET
[debug] --- VERSION_REPORT
[debug] - CommandClass: COMMAND_CLASS_MANUFACTURER_SPECIFIC
[debug] -- Version: 2
[debug] -- Commands:
[debug] --- MANUFACTURER_SPECIFIC_GET
[debug] --- MANUFACTURER_SPECIFIC_REPORT
[debug] --- DEVICE_SPECIFIC_GET
[debug] --- DEVICE_SPECIFIC_REPORT
[debug] - CommandClass: COMMAND_CLASS_BASIC
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- BASIC_GET
[debug] --- BASIC_REPORT
[debug] --- BASIC_SET
[debug] ------------------------------------------
[debug] 
[debug]  COMMAND_CLASS_DOOR_LOCK->DOOR_LOCK_OPERATION_GET args: {} cb: true
[debug]  COMMAND_CLASS_BATTERY->BATTERY_GET args: {} cb: true
[debug]  COMMAND_CLASS_BATTERY->BATTERY_GET args: {} cb: true
[debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: null result: { 'Battery Level (Raw)': <Buffer 5d>, 'Battery Level': {} }
[debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: null result: { 'Battery Level (Raw)': <Buffer 5d>, 'Battery Level': {} }
[debug]  COMMAND_CLASS_DOOR_LOCK DOOR_LOCK_OPERATION_GET args: {} err: null result: { 'Door Lock Mode (Raw)': <Buffer 00>,
  'Door Lock Mode': 'Door Unsecured',
  'Properties1 (Raw)': <Buffer 00>,
  Properties1: 
   { 'Inside Door Handles Mode': 0,
     'Outside Door Handles Mode': 0 },
  'Door Condition (Raw)': <Buffer 02>,
  'Door Condition': 2,
  'Lock Timeout Minutes (Raw)': <Buffer 00>,
  'Lock Timeout Minutes': 0,
  'Lock Timeout Seconds (Raw)': <Buffer 00>,
  'Lock Timeout Seconds': 0 }
[debug] get locked
[debug] get measure_battery
[debug] get alarm_battery
[debug] set locked true
[debug]  COMMAND_CLASS_DOOR_LOCK
					->DOOR_LOCK_OPERATION_SET args: { 'Door Lock Mode': 'Door Secured' }
[debug] set locked false
[debug]  COMMAND_CLASS_DOOR_LOCK
					->DOOR_LOCK_OPERATION_SET args: { 'Door Lock Mode': 'Door Unsecured' }
-------------------------------------------------

Stopping...

--- INFO: com.popp has been killed ---
App uninstalled

**Comment by bumer0** [comment]
[debug]  COMMAND_CLASS_DOOR_LOCK
					->DOOR_LOCK_OPERATION_SET args: { 'Door Lock Mode': 'Door Unsecured' }
[debug] { Error: timeout
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1245)
    at JSON.parse (<anonymous>)
    at jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1143)
    at Array.map (<anonymous>)
    at process.<anonymous> (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v1/helpers/client.js:1:1231)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'timeout' }
[debug] node.CommandClass['COMMAND_CLASS_SENSOR_BINARY'].on('report') arguments: { '0': { value: 3, name: 'SENSOR_BINARY_REPORT' },
  '1': 
   { 'Sensor Value (Raw)': <Buffer ff>,
     'Sensor Value': 'detected an event',
     'Sensor Type (Raw)': <Buffer 0a>,
     'Sensor Type': 'Door/Window' },
  '2': null }

**Comment by bumer0** [comment]
->DOOR_LOCK_OPERATION_SET args: { 'Door Lock Mode': 'Door Unsecured' }
[debug] set locked true
[debug]  COMMAND_CLASS_DOOR_LOCK
					->DOOR_LOCK_OPERATION_SET args: { 'Door Lock Mode': 'Door Secured' }
[debug] node.CommandClass['COMMAND_CLASS_SENSOR_BINARY'].on('report') arguments: { '0': { value: 3, name: 'SENSOR_BINARY_REPORT' },
  '1': 
   { 'Sensor Value (Raw)': <Buffer 00>,
     'Sensor Value': 'idle',
     'Sensor Type (Raw)': <Buffer 0a>,
     'Sensor Type': 'Door/Window' },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_NOTIFICATION'].on('report') arguments: { '0': { value: 5, name: 'NOTIFICATION_REPORT' },
  '1': 
   { 'V1 Alarm Type (Raw)': <Buffer 00>,
     'V1 Alarm Type': 0,
     'V1 Alarm Level (Raw)': <Buffer 00>,
     'V1 Alarm Level': 0,
     'Reserved (Raw)': <Buffer 00>,
     'Notification Status (Raw)': <Buffer ff>,
     'Notification Status': 'On',
     'Notification Type (Raw)': <Buffer 06>,
     'Notification Type': 'Access Control',
     'Event (Raw)': <Buffer 16>,
     Event: 22,
     'Properties1 (Raw)': <Buffer 00>,
     Properties1: { 'Event Parameters Length': 0, Sequence: false },
     'Event (Parsed)': 'Window/Door is open' },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_SENSOR_BINARY'].on('report') arguments: { '0': { value: 3, name: 'SENSOR_BINARY_REPORT' },
  '1': 
   { 'Sensor Value (Raw)': <Buffer ff>,
     'Sensor Value': 'detected an event',
     'Sensor Type (Raw)': <Buffer 0a>,
     'Sensor Type': 'Door/Window' },
  '2': null }
[debug] set locked false
[debug]  COMMAND_CLASS_DOOR_LOCK
					->DOOR_LOCK_OPERATION_SET args: { 'Door Lock Mode': 'Door Unsecured' }
[debug] set locked true
[debug]  COMMAND_CLASS_DOOR_LOCK
					->DOOR_LOCK_OPERATION_SET args: { 'Door Lock Mode': 'Door Secured' }
[debug] set locked false
[debug]  COMMAND_CLASS_DOOR_LOCK
					->DOOR_LOCK_OPERATION_SET args: { 'Door Lock Mode': 'Door Unsecured' }
[debug] set locked true
[debug]  COMMAND_CLASS_DOOR_LOCK
					->DOOR_LOCK_OPERATION_SET args: { 'Door Lock Mode': 'Door Secured' }
[debug] set locked false
[debug]  COMMAND_CLASS_DOOR_LOCK
					->DOOR_LOCK_OPERATION_SET args: { 'Door Lock Mode': 'Door Unsecured' }
[debug] set locked true
[debug]  COMMAND_CLASS_DOOR_LOCK
					->DOOR_LOCK_OPERATION_SET args: { 'Door Lock Mode': 'Door Secured' }
[debug] node.CommandClass['COMMAND_CLASS_NOTIFICATION'].on('report') arguments: { '0': { value: 5, name: 'NOTIFICATION_REPORT' },
  '1': 
   { 'V1 Alarm Type (Raw)': <Buffer 00>,
     'V1 Alarm Type': 0,
     'V1 Alarm Level (Raw)': <Buffer 00>,
     'V1 Alarm Level': 0,
     'Reserved (Raw)': <Buffer 00>,
     'Notification Status (Raw)': <Buffer ff>,
     'Notification Status': 'On',
     'Notification Type (Raw)': <Buffer 06>,
     'Notification Type': 'Access Control',
     'Event (Raw)': <Buffer 16>,
     Event: 22,
     'Properties1 (Raw)': <Buffer 00>,
     Properties1: { 'Event Parameters Length': 0, Sequence: false },
     'Event (Parsed)': 'Window/Door is open' },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_SENSOR_BINARY'].on('report') arguments: { '0': { value: 3, name: 'SENSOR_BINARY_REPORT' },
  '1': 
   { 'Sensor Value (Raw)': <Buffer ff>,
     'Sensor Value': 'detected an event',
     'Sensor Type (Raw)': <Buffer 0a>,
     'Sensor Type': 'Door/Window' },
  '2': null }

**Comment by bumer0** [comment]
[POPP_atom.log](https://github.com/mruiter/com.popp/files/1618636/POPP_atom.log)

**Comment by bumer0** [comment]
[POPP.COM_v2.0.1.LOG](https://github.com/mruiter/com.popp/files/1618978/POPP.COM_v2.0.1.LOG)

v 2.0.1

**Comment by mruiter** [comment]
I've added the notification to the 2.0.2 version of the beta on my github.
Could you please check... A re-pair of the devices is needed i guess.

**Comment by bumer0** [comment]
I did re-pair of the devices
[POPP v2.0.2_.log](https://github.com/mruiter/com.popp/files/1661421/POPP.v2.0.2_.log)

doesn't work 
I do not see any action in the Flow  and I do not see any changes in the device
log in attached

**Comment by mruiter** [comment]
Mmm the device card should have a extra icon with a contact alarm

**Comment by mruiter** [comment]
I thing i already see the problem. Im on my phone right now so i Will try to fix iT early in the morning tomorrow . Sjorry for the booboo

**Comment by bumer0** [comment]
I use homebridge and in my iphone i see additional contact alarm and it working correct 
I think just one problem only:  additional card for flow

**Comment by mruiter** [comment]
If the contact alarm is there the flow cards for iT should be auto created by homey 🤔

Verstuurd vanaf mijn iPhone

**Comment by bumer0** [comment]
only 2 card in flow (lock /unlock)
<img width="267" alt="2018-01-24 23 39 24" src="https://user-images.githubusercontent.com/31984665/35355910-e6479b78-015f-11e8-9c55-9a7fb71c0f59.png">
<img width="298" alt="2018-01-24 23 39 35" src="https://user-images.githubusercontent.com/31984665/35355911-e66b69b8-015f-11e8-8343-c2dc56179881.png">

**Comment by AdyRock** [comment]
Was the input ever fixed?

I have just added one of these to Homey but all I see is the option to switch it off/on in devices and the just locked and just unlocked flow options as posted by bumer0.
I'm using Homey version 1.5.11 and 2.0.4 of the app and I have removed and repaired the device (several times). Sometimes it fails to pair properly so I have to remove it and tray again. A couple of times it had the battery status but I can't seem to get that back now. I have rebooted Homey and reset the unit with a 10 second press of the pair button (several times).

If I connect the modules input to ground the relay switches back again and the light flashes but I see nothing reported anywhere in Homey.

Also the manual for the unit says the default on time is 3 seconds and can be adjust using parameter 0.
I find that unlocking stays active until I switch it off again or connect the input terminal to ground.
Finally, switching the unit off using the input terminal does not report back to the slider in Homey so it gets out of sync.

I would be grateful for any help to get this working.

**Comment by osochor** [comment]
Unfortunately, the External Dry Contact still does not work.
Homey v2.1.1, Popp app v2.0.6 beta.

**Comment by AdyRock** [comment]
It's working for me with the Popp app V2.0.6 beta.
I use it to make homey remind us if the door has been left open. 
There are occasions where the transition is missed but I think this is a zwave issue.

**Comment by mruiter** [comment]
Solved in latest versions
