### ISSUE TITLE
Srike lock control

### ISSUE THREAD

**Issue by Oy1974** [mruiter/com.popp#13]
Using a "Popp strike lock"  and i noticed 2 things. 1 thats a big problom because its draining my battery in just 12 hours to a point that its has not enough power to operate the internal relays.

Second acording the technical information. its hase a no and nc contact. But its the otherway round the drawing says.

When instaling it like this i have a nc contact, so using the other contact so having the normaly open. Could it be that therefor it drain the batt??

![popp](https://user-images.githubusercontent.com/32013370/36943953-c73e74ee-1f92-11e8-8d5d-c98bda9da6c1.JPG)

**Comment by mruiter** [comment]
I dont have the device myself. I Know a lot have it on constant power. Nevertheless these last weeks there where a lot of bugs fixed with the FLIRS protocol that does most of the battery saving. Should be fixed
