### ISSUE TITLE
[Request] Support for Popp Z-Wave CO Detector

### ISSUE THREAD

**Issue by ks2018ks** [mruiter/com.popp#17]
Hi Any chance support can be added for Popp Z-Wave CO Sesnor please?
http://www.popp.eu/products/sensors/co-sensor/
 (Product Code: 004407)

http://manuals-backend.z-wave.info/make.php?lang=en&sku=pope004407&type=popp

**Comment by mruiter** [comment]
Already available in the Beta Version of the App in the appstore
I dont have the device myself so please test if all is ok and let me know.

**Comment by ks2018ks** [comment]
Thank you I missed that.  Seems to include properly

I get this:
![image](https://user-images.githubusercontent.com/37977911/38248723-507a3c96-3741-11e8-9d24-e5d5f4c83527.png)

Settings like this:
![image](https://user-images.githubusercontent.com/37977911/38248793-7ddb08e6-3741-11e8-876c-ab27cb9f676d.png)
& this:
![image](https://user-images.githubusercontent.com/37977911/38248824-8fb63658-3741-11e8-8fb9-e51182810139.png)


By the way the include button is on the back (se: http://manuals-backend.z-wave.info/make.php?lang=en&sku=pope004407&type=popp) not like the picture in the inclusion routine which seems to point to the test button on the front


Thank you.
