### ISSUE TITLE
Keypad 700045 Not possible to add

### ISSUE THREAD

**Issue by MartinG72** [mruiter/com.popp#21]
Problem with adding the keypad, tried many times with no result.
Also did a reset of the keypad and restarted the Homey without results.

The firmware I'm running is Homey Firmware Version: 1.5.9

Maybe I'm doing somthing wrong. 
Tryed adding it and then pressed 1 and then * in MM

Regards Martin

**Comment by mruiter** [comment]
Did it see it the first time but just hang in the process ?

There is a huge bug in the zwave core . Homey is pretty much crippled and doesnt pair with S2 secure devices 

It has been reported to athom 2 months ago

https://github.com/athombv/homey-issues-dp/issues/158

Verstuurd vanaf mijn iPad

**Comment by MartinG72** [comment]
Ok. 
Did not see any pairing.

**Comment by MartinG72** [comment]
Added the keypad using "add generic z-wave device" and the keypad ws added using 4->*.
Now i can see the keypad and it will do tamperwarning. When i dile the correct code the Popp app craches

**Comment by mruiter** [comment]
I got the crash report . Will fix iT this weekend . Thx for the test

Verstuurd vanaf mijn iPhone

**Comment by pmolensky** [comment]
hi @mruiter, did you make any progress? I have exactly the same issue.

At first I was unable to add the keypad. Somehow I managed to add it. After which the popp app crashes when receiving any user scene.

I send you two crash logs, which might help you in investigation. As a bonus, I don't see any flow triggers, conditions or actions for the popp keypad in the editor.


**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**:
* **Desktop Platform**: Windows 10 (1803)
* **Desktop App Version**: 1.0.4


**If related to a Homey App:**
* **Homey App Version**: beta v2.0.4
* **Homey App Log Code**:
  * 20180714: 1f2679d3-15cb-4c5c-ae42-6657a53955d0
  * 20180712: d91095f1-6fc7-4cfe-9579-b1414f04765d
* **Affected Devices (preferably product codes)**:
  * Popp keypad 70045


**What did you try to achieve?**
1. removed and reinstalled the app
2. removed and re-included the keypad
3. search this github and forum.athom.com for similar issues.
  * on github I found this issue
  * on the forum I found a [comment in discussion [APP] Z-Wave POPP Devices support for Homey](https://forum.athom.com/discussion/comment/74720/#Comment_74720), but I can't contribute to that discussion (role=unconfirmed)
4. reset my z-wave network, removing all devices


**What did you expect as result?**
I expect to receive the different user scenes (1-20) and special scenes (21, 22 & 23) so I can use these as flow triggers. 


**What was the result?**
When observing the device, it crashes (device icon changes temporary to question mark).
![image](https://user-images.githubusercontent.com/29775347/42725516-f68214a4-8784-11e8-9b2d-93b78e6ea110.png)


**Any other remarks**
I don't see any flow triggers, conditions or actions for the popp keypad in the editor.

**Comment by pmolensky** [comment]
I created a PR (#26) with a fix for the crash issue.
Stubling on the next error. After adding some debug log and a catch-statement I see `Error: invalid_device`.

> ✓ Validating app...
✓ Homey App validated successfully against level `debug`
✓ Packing Homey App...
✓ Installing Homey App on `Homey` (http://xxx.xxx.xxx.xxx:80)...
✓ Homey App `com.popp` successfully installed
✓ Running `com.popp`, press CTRL+C to quit
─────────────── Logging stdout & stderr ───────────────
(node:18208) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 __appInit listeners added. Use emitter.setMaxListeners() to increase limit
2018-07-17 02:12:43 [log] [PoPPZwave] PoPP Z-wave app is running...
2018-07-17 02:12:44 [log] [ManagerDrivers] [700045] [0] ZwaveDevice has been inited
2018-07-17 02:13:11 [log] [ManagerDrivers] [700045] [0] Triggering sequence: 57 remoteValue { button: '23', scene: 'Key Pressed 1 time' }
2018-07-17 02:13:11 [log] [ManagerDrivers] [700045] [0] { Error: invalid_device
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1103)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1001)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11) message: 'invalid_device' }

**Comment by pmolensky** [comment]
I'm commenting here to the (I suspect related) [forum discussion](https://forum.athom.com/discussion/comment/75136/#Comment_75136) (_I have an account, but I'm not allowed to comment there_ :disappointed: ).
While the app does not crash anymore for me, I have two remaining issues:
1. `Error: invalid_device`
2. Device doesn't show in flow editor

Do you want to continue in this issue or should I open one or two new issues? @mruiter
I suspect they're unrelated as I'm able to partly solve the second issue.

I've tried to debug what is and what isn't happening by comparing the com.popp-code to working apps/devices. As this is my first attempt in developing a Homey app, I'm afraid I'm not making any substantial progress at the moment.

When I [remove the device/driver filters](https://gist.github.com/pmolensky/0a4b620aba45407aaee5aeec95571ae0/revisions) `args` in flow triggers from the app.json, the **POPP app** appears in the flow editor, but not as a **device**.

**Comment by mapulu** [comment]
It's working on Homey 2.x

**Comment by mruiter** [comment]
Confirmed working in latest versions of app
