### ISSUE TITLE
004001 - PoPP Smoke Detector and Siren - Card not registered

### ISSUE THREAD

**Issue by chrmat** [mruiter/com.popp#22]
Get an error message "card not registered"  when trying to use 004001 - PoPP Smoke Detector and Siren in flows. App version v2.0.4 - 05.03.18, Homey Firmware Version: 1.5.11. See Screenshot
![image](https://user-images.githubusercontent.com/36868426/41244238-bf9ce512-6da4-11e8-9bdd-5201214d4e81.png)

**Comment by mruiter** [comment]
Did you came from the 1.x series ? Then you need a repair of the device 

Verstuurd vanaf mijn iPhone

**Comment by chrmat** [comment]
Hi, I removed the PoPP Smoke Detector and Siren from the z-wave network, upgraded the app to latest beta, added the device.

**Comment by chrmat** [comment]
Any update on this issue? It is still present in beta 2.06

**Comment by tamesoud** [comment]
same issue here, card_not_registered when including the siren in an alarm flow.
The siren can be turned on and off when I just select it on in devices, it just doesn't work when put in a flow.
beta 2.06

thanks

**Comment by rindlerblabla** [comment]
Know that there are some issues with the smoke detector. Is the siren still not working in flows?

**Comment by tamesoud** [comment]
Sorry, I wouldn’t know. I returned the smoke detector/siren after waiting for a couple of weeks for an update of the app. I do have the solar siren outside and am able to turn it on in a flow as part of my alarm.

Tames

**Comment by rindlerblabla** [comment]
Okay! Thanks for your reply!

**Comment by mruiter** [comment]
Solved in latest versions
