### ISSUE TITLE
004001 - PoPP Smoke Detector and Siren - Smoke alarm not triggering flows

### ISSUE THREAD

**Issue by chrmat** [mruiter/com.popp#23]
I have the 004001 - PoPP Smoke Detector and Siren and I am trying to start a flow when the fire alarm is triggered. The flow works when it hit the test button, but it is not started by using the test button on the smoke detector, or by starting the smoke alarm by blowing smoke in it.

The test was done using the stable version of the app ( v1.1.7 - 28.08.17) and with  Homey Firmware Version 1.5.11. 

![image](https://user-images.githubusercontent.com/36868426/41249873-9b721534-6db5-11e8-9c26-c7e6211efd7d.png)

**Comment by chrmat** [comment]
In addition the Smoke Alarm is not show under "Insights". It only has "Battery", "Battery Alarm" and "Turned on". "Turned on" is when the siren is turned on manually used as a siren, and not when the smoke alarm has been triggered.


![screenshot from 2018-08-12 21-50-50](https://user-images.githubusercontent.com/36868426/44005857-609fe2ec-9e7a-11e8-8595-528e02b4628c.png)

**Comment by mruiter** [comment]
Insights is being removed completely in the next month or so . No need for those anymore with the upcoming new app and firmware of homey

**Comment by chrmat** [comment]
Hi, the main issue is not that "Smoke Alarm" is not show under "Insights". But the fact that Homey does not seem to receive or "interpret" that the Popp smoke detector detects a fire. Hopefully that will be fixed in the new app and firmware of homey.
