### ISSUE TITLE
Popp strike how to adjust timing to open

### ISSUE THREAD

**Issue by Pim65** [mruiter/com.popp#24]
Hi all,

I added this Popp module to my homey, but I cant adjust the timing from the open signal.. So it is either on or off. I like to adjust the time to open for example 5 sec or so.
Who can advise me on this.

Thanks in advance!

Pim

**Comment by mruiter** [comment]
Best way to do this is in a flow. With the coundown app. When open let the countdown start and when the countdown from 5 is to zero make it close
