### ISSUE TITLE
Smoke Detector shows always 100% Batt even if the Battery is low

### ISSUE THREAD

**Issue by Andi1927** [mruiter/com.popp#25]
The Smokedector shows alway 100% Batt. Even if the Detector start to alarm Low Batt with acustic Signal. This is with the Beta and the stable version the same.

**Comment by chrmat** [comment]
Same issue with mine

**Comment by chrmat** [comment]
Hi, this seems to be an issue with the Popp Smoke detectors themselves, and not the app. Someone in this thread has received confirmation from Popp that they send  a battery status with 100%. This only switches to zero, when the battery alarm is already active, no values in between. 

Source:
https://community.openhab.org/t/which-smoke-detector-groups-notification-etc/32121/22
