### ISSUE TITLE
004001 - PoPP Smoke Detector and Siren - Smoke alarm not triggering flows

### ISSUE THREAD

**Issue by chrmat** [mruiter/com.popp#27]
I have the 004001 - PoPP Smoke Detector and Siren and I am trying to start a flow when the fire alarm is triggered. The flow works when I test the flow in the menu, but it is not started by using the test button on the smoke detector, or by starting the smoke alarm by blowing smoke in it. It seems like the event that the Popp Smoke Detector sends when it detects smoke does not trigger anything in Homey. 

The test was done using the stable version of the app ( v1.1.7 - 28.08.17) and with Homey Firmware Version 1.5.11.
![image](https://user-images.githubusercontent.com/36868426/44912054-52d8bb80-ad29-11e8-90fc-02cf386ba1ef.png)

**Comment by Caros2017** [comment]
Hi @chrmat,

If I read the documentation on the POPP website, it doesn't say anything about Z-wave triggering when using the test button:
_"A button on the device can be used to test the smokebox, the electronics and the battery. In addition the device has an integrated test functionality to make manual tests with Aerosol unnecessary. The battery warning gets send for at least 30 days. During this time the smoke sensor stays fully functional."_

Nevertheless it's strange that it's not even working when you trigger the alarm itself with smoke. Few quistions:
- Is the sound alarm triggered with smoke?
- When you trigger it with smoke and at the same time you look into Homey under the device, is the Smoke alarm then 'active'?
- Have you tried the beta version of the app?

**Comment by chrmat** [comment]
Hi,

- I have 4 Popp 004001 devices. The sound alarm is triggered with smoke, (and by pressing the test button) and after a while the sound alarm is triggered on all 4 devices.  This probably happens because they are automatically meshed to each other by the default setting of configuration parameter 5 and 6. See manual at http://manuals-backend.z-wave.info/make.php?lang=en&sku=POPE004001. Can it be that these should be changed for Homey to react to the alarm? Would be nice if these parameters could be updated from the settings.

-I did not look if the device was active in Homey when the alarm was triggered. I  will check when my tenants are away.
-Had some other issues with beta 2.04, "cards not registered", and have not tried it since.

**Comment by asteman** [comment]
I can confirm  smoke is not indicated by Homey when testing with real smoke.
Homey 1.5.13
Popp beta 2.0.6

**Comment by Caros2017** [comment]
Same issue here
Homey stable 2.0.0
Popp beta 2.0.6

**Comment by rindlerblabla** [comment]
Is this issue solved yet?

@mapulu Do you know anything more about this? Wrote to you on Slack about it a while ago, and you wrote back that there is some binary setting missing (don't really know myself). Is this code added to the beta? Am thinking of buying those sensors...

**Comment by mapulu** [comment]
I got no feedback if it works or not. 

So I can not tell for sure. If you bought them please send me a message if they work or not.
If not it should be fixable with your help in a short time period.

**Comment by rindlerblabla** [comment]
@mapulu Have now two sensors myself and can confirm that nothing is triggered by "real" fire. 

How can I help you solve this issue?

**Comment by chrmat** [comment]
I am also willing to help. I have had these smoke sensors for years, and they have never worked with Homey. The only thing that works is turning the siren on and off.

**Comment by mapulu** [comment]
Anyone familiar with cli install?
Send me an e-mail
mapulu@t-online.de

**Comment by chrmat** [comment]
> Edit: I asked here for CLI install and got response and debug data. A solution should be available soon.

Hi, just curious on the progress.. Did you find a solution?

**Comment by mapulu** [comment]
Sorry no. Still waiting for a response. 
Would be better if someone could borrow me the device.

**Comment by chrmat** [comment]
> Sorry no. Still waiting for a response.
> Would be better if someone could borrow me the device.
Anything I can do without borrowing you the device?

**Comment by rindlerblabla** [comment]
Just to let you other users know. @mapulu has found the issue and have a fix for it. Have alpha tested it myself and can confirm that it's working. Just be patient and he will make a PR to the app.

**Comment by mapulu** [comment]
Before I add the PR I want to do some additional testing with the popp 004001 smoke sensor I bought today. So expect the PR early next week.

**Comment by chrmat** [comment]
> Before I add the PR I want to do some additional testing with the popp 004001 smoke sensor I bought today. So expect the PR early next week.

How did the testing go?

**Comment by rindlerblabla** [comment]
At least with test spray it is now working. Think you can close this issue.

**Comment by chrmat** [comment]
> At least with test spray it is now working. Think you can close this issue.

In which version of the app is it working?

**Comment by rindlerblabla** [comment]
2.0.12.

**Comment by chrmat** [comment]
> 2.0.12.

Ok, thanks I'l do a new test later today. BTW, that app 2.0.12 has release date 10.09.2019, which is before mapulu started his work, so it seems a bit strange that it has been fixed..

**Comment by rindlerblabla** [comment]
Hm. Yes, that's odd. However I can confirm that test spray triggered my smoke alarm flows. Even battery alarm does the same, hehe. Feature or bug?

**Comment by rindlerblabla** [comment]
By mistake I put old batteries in my smoke sensor. That triggered the smoke alarm (and flows). But it's probably more related to the smoke sensor than to the app?

Also the battery alarm is not reset eventhough I changed battery and it still show 1% battery level. Will buy new batteries and report back if this fix the issue.
