### ISSUE TITLE
Qubino 3-Phase Smart Meter

### ISSUE THREAD

**Issue by edorf83** [mruiter/com.popp#29]
Has downloaded Qubino app, but when I enter the device. then it will appear as an unknown device.
What can the problem be?
![qubino 3-phase smart meter](https://user-images.githubusercontent.com/43094467/45266800-2fb4b700-b461-11e8-86f9-3ba15884b910.jpg)

**Comment by mruiter** [comment]
Dont know , you are on the popp app github and you talk about qubino. Guess you took a wrong turn somewhere 

Verstuurd vanaf mijn iPhone
