### ISSUE TITLE
Heatit Z-Water

### ISSUE THREAD

**Issue by edorf83** [mruiter/com.popp#30]
Has installed this device to control my waterborne heat. But do not find it in any app? Anyone who knows anything about this?

![z-water](https://user-images.githubusercontent.com/43094467/45266914-2cbac600-b463-11e8-8609-9d01e8bcca87.jpg)

![z-water_2](https://user-images.githubusercontent.com/43094467/45266917-36442e00-b463-11e8-92f8-4d51c175d18d.jpg)

**Comment by mruiter** [comment]
Not in the popp github again a wrong turn 

Verstuurd vanaf mijn iPhone
