### ISSUE TITLE
Popp Solar Siren 2

### ISSUE THREAD

**Issue by Shadowz7** [mruiter/com.popp#31]
Hello,
I bought a new solar siren from Popp.
With the stable app a use was not possible.
The siren can be triggered with the beta version, but the sensors are not supported.
Does anyone know if this is a bug of my siren or the app?

![screenshot_20181018-113606_homey](https://user-images.githubusercontent.com/44264748/47156619-cb9ad380-d2e7-11e8-9988-1793e9ea30b4.jpg)

**Comment by mruiter** [comment]
IT should report in after Some time and give you the temperatuur . How long is iT paired already ?

Verstuurd vanaf mijn iPhone

**Comment by Shadowz7** [comment]
Its 2 days paired. It still does not show the temperature or an aktiv Tampr arm.
Its an POPE700854.

**Comment by Shadowz7** [comment]
6 days later, its the same problem.

**Comment by mruiter** [comment]
Please do a repair since iT works on other sirens . Maybee the initial pair went wrong 

Verstuurd vanaf mijn iPhone

**Comment by Shadowz7** [comment]
[Flyer_POPP_Outdoor-Siren2_En.pdf](https://github.com/mruiter/com.popp/files/2505200/Flyer_POPP_Outdoor-Siren2_En.pdf)
700854 - Solar Outside Siren 2
And we both talk about the 2nd generation of popp sirens?
Since this is not included in the overview of the app.

**Comment by mruiter** [comment]
We if iT gets detected then iT uses the same zwave firmware because else iT would have a different product id and would not be seen 
So there should be no zwave difference if popp is using the zwave fuidelines 

Verstuurd vanaf mijn iPhone

**Comment by Marlark** [comment]
@Shadowz7 did you get this working? I just got a version 2 also and i installed the Beta version and the siren works and the tamper trigger on the mounting but the temp dont seam to work. There is a additional siren Icon that turns up after repairing the unit to the Beta version of the app.

// Teddy

**Comment by tamesoud** [comment]
same issue here

**Comment by rindlerblabla** [comment]
Seems like there is a duplicate with the 10 year smoke detector in some way? At least the #38 issue indicates that. Could you provide device ID, profile ID and so on, when you click on advanced settings on the device, or find the device under developer.athom.com?

**Comment by mapulu** [comment]
The Popp Solar Siren 2 have no temperature sensor. In the description on the popp website it is clearly missing. Also the command class is missing.
