### ISSUE TITLE
123610 68G not detected correctly

### ISSUE THREAD

**Issue by jandan67** [mruiter/com.popp#32]
Hello!
I have a 123610 68G , but the Homey App does not detect it correctly, it only adds it as a generic z-wave device.
// Best Regards
Jan

**Comment by urbanskil** [comment]
+1

**Comment by JohanBendz** [comment]
@jandan67 Can you add the device as a generic Z-wave device and get back with the product information? (Node information; Node ID, Manufacturer ID, Product type ID, Product ID)

**Comment by jandan67** [comment]
Node ID:  ??  I can find DeviceID: 29 , but no NodeID. Where can I find this value?
Manufacturer ID:  340
Product type ID:  4352
Product ID:  1

//  Janne


Från: Johan Bendz <notifications@github.com>
Skickat: den 1 april 2019 21:11
Till: mruiter/com.popp <com.popp@noreply.github.com>
Kopia: jandan67 <janne.d@live.se>; Mention <mention@noreply.github.com>
Ämne: Re: [mruiter/com.popp] 123610 68G not detected correctly (#32)


@jandan67<https://github.com/jandan67> Can you add the device as a generic Z-wave device and get back with the product information? (Node information; Node ID, Manufacturer ID, Product type ID, Product ID)

**Comment by JohanBendz** [comment]
@jandan67 Ah, my fault.. I mean device ID :)
Thanks for the info. I'll look into adding the device.

// Johan

**Comment by mruiter** [comment]
No info received in 6 months
