### ISSUE TITLE
Popp smart outdoor plug 700397

### ISSUE THREAD

**Issue by ghost** [mruiter/com.popp#36]

**Comment by dommotica** [comment]
Is this Device supported?

**Comment by MackanS** [comment]
I've got 700397 too and it doesn't seem to be supported... yet. Would be nice if it got supported.

**Comment by MackanS** [comment]
Please add support for 700397. I am willing to do testing of the plug. :)

**Comment by JohanBendz** [comment]
Same as #41

**Comment by mapulu** [comment]
I will add it

**Comment by P4k3** [comment]
> I will add it

How is it going? Winter is coming and it would be awesome to get graphs of powerconsumption of the car heaters.. :)

**Comment by mapulu** [comment]
Should be soon available. Please give feedback if it works or not (because I don't have that device)
It is already merged into the branch beta. 
mruiter should have submitted it into Homey Apps and Athom have to approve it and then mruiter have to publish it.

**Comment by mhoogenbosch** [comment]
When installing the beta through CLI I get a few warnings: 

Warning: drivers.701202 is missing an array 'energy.batteries' because the capability measure_battery is being used. Specifying the type of battery will be required in the future.

I'll try and add the outdoor plug this afternoon.

**Comment by mhoogenbosch** [comment]
Installed the beta. Took a while for the Generic Zwave device to be removed, but that worked. I could add it as a 'smart outdoor plug', but after adding the pop application crashes. The device has an ID on the zwave page on developer. Let me know if i can do something to help you out.

**Comment by mapulu** [comment]
Sorry I made careless mistake that shouldn't happen.
Only one } too much.
I send a PR to the beta branch which should not crash the app.


You can ignore the warning about "energy.batteries", it seems for a future feature which is called "Homey Energy"

**Comment by mhoogenbosch** [comment]
Right, can happen, ill try again tomorrow.

Regards

Martijn

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: mapulu <notifications@github.com>
Verzonden: Thursday, August 22, 2019 8:54:58 PM
Aan: mruiter/com.popp <com.popp@noreply.github.com>
CC: Martijn Hoogenbosch <martijn@texel.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [mruiter/com.popp] Popp smart outdoor plug 700397 (#36)


Sorry I made careless mistake that shouldn't happen.
Only one } too much.
I send a PR to the beta branch which should not crash the app.

You can ignore the warning about "energy.batteries", it seems for a future feature which is called "Homey Energy"

**Comment by mhoogenbosch** [comment]
Beta works now!

**Comment by MorganLindqvist** [comment]
> I send a PR to the beta branch which should not crash the app.

Hi @mapulu
Do you have a time plan on when this could be pushed to Athom (as beta or master)?

**Comment by mapulu** [comment]
The developer is @mruiter
I think soon, it pending for approval by athom.

**Comment by MorganLindqvist** [comment]
Version 2.0.12 on Homey works, thanks. @mruiter.
