### ISSUE TITLE
Popp 10 years smoke sensor/ siren

### ISSUE THREAD

**Issue by Mindsuk** [mruiter/com.popp#38]
Thank you for your work! 
I tried to add a 10 years smoke sensor three times, but Homey think it‘s a Popp outdoor solar siren! 😕 please help

**Comment by Mindsuk** [comment]
Hi! Could you please give me a feedback?

**Comment by Mindsuk** [comment]
Marco? Is it possible to give me an Feedback? 🤔

**Comment by JohanBendz** [comment]
@Mindsuk Can you add the device as a generic Z-wave device and get back with the product information? (Node information; Node ID, Manufacturer ID, Product type ID, Product ID)

**Comment by Mindsuk** [comment]
@JohanBendz 

Yes I will do!

**Comment by Mindsuk** [comment]
@JohanBendz 

Node information: Solar Outdoor Siren
Node ID / Device ID: 106
Manufacturer ID: 340
Product type ID: 4
Product ID: 2

Thank you!
