### ISSUE TITLE
Popp Power Plug POPE700793

### ISSUE THREAD

**Issue by Blutkeks** [mruiter/com.popp#39]
This device does not seem to be supported now. But would be nice If. :-) 
Only the on/off functionality works but no energy monitoring. I dont know if there is much difference between the Power Plug and the Indor plug. 
So if someone would add the device to homey, I would be very grateful. Thx for your work guys.

![popp](https://user-images.githubusercontent.com/47060416/51789439-2f575700-2189-11e9-8bfd-274e2c7518b9.JPG)

**Comment by JohanBendz** [comment]
https://products.z-wavealliance.org/products/2955

**Comment by mapulu** [comment]
Its added to v2.0.10
please send feeeback if it works

**Comment by mruiter** [comment]
Confirmed working in latest versions of app
