### ISSUE TITLE
 I can not add a smoke detector

### ISSUE THREAD

**Issue by benotje** [mruiter/com.popp#4]
When I add a smoke detector, he adds a Solar Outside Siren and he indicates that there is no connection with the wrong code invalid_commandClass_COMMAND_CLASS_SENSOR

**Comment by JPe2** [comment]
@benotje   @mruiter will need the node information to be able to add your device (info shown when you try to add your device)

**Comment by mruiter** [comment]
the device is added into the app, version 1.1.3 is now in the appstore
