### ISSUE TITLE
Including error - secure flow stop

### ISSUE THREAD

**Issue by perpatrik79** [mruiter/com.popp#40]
I tried to include "secure flow stop - valve" today. It worked fine to include but after the inclution finished it appeared as "strike lock control" in the Homey app. I am using the beta version 2.0.6 and the Homey version 2.0.4.
//Patrik

**Comment by mapulu** [comment]
So you device may have the wrong product-id.
It is not so easy to fix. The best thing would be get it replaced by popp.
But I could also help you. If you still need help please contact me at Homey Community
[@mapulu](https://community.athom.com/new-message?username=mapulu&title=Popp-App)

**Comment by mruiter** [comment]
Can only be solved with a replacement from Popp with a correct firmware
