### ISSUE TITLE
Popp outdoor switch

### ISSUE THREAD

**Issue by rvqrat** [mruiter/com.popp#41]
Hi,

Does this Popp Smart Outdoor Plug (SKU: POPE700397) work with this app?
http://manual.zwave.eu/backend/make.php?lang=en&sku=POPE700397

And if not, is it possible to add it in the app?

Thank's!

**Comment by JohanBendz** [comment]
https://products.z-wavealliance.org/products/2842
@mruiter, do tell if you want help adding devices that are requested.

**Comment by rindlerblabla** [comment]
@JohanBendz Marco wrote on Slack: "Popp app is maintained by users that have popp devices and send in pulls. That doesn’t happen anymore. So no updates :see_no_evil:".

So guess that's a 'yes' to your question! Hehe.

**Comment by mhoogenbosch** [comment]
Right, I just bought this device as well and is now added as regular z-wave device. Works like a charm but doesnt report electricity or anything. So if anyone can give an heads up how to add devices ?

**Comment by PapRIkaNL** [comment]
> Hi,
> 
> Does this Popp Smart Outdoor Plug (SKU: POPE700397) work with this app?
> http://manual.zwave.eu/backend/make.php?lang=en&sku=POPE700397
> 
> And if not, is it possible to add it in the app?
> 
> Thank's!

It does work but just as simple Z-wave device, no energy monitoring. The app also does not get installed but in the end it will work turning it on or off. Can the dfeveloper help? Maybe we should donate something?

**Comment by mhoogenbosch** [comment]
Would not mind donating a few euros but would like to know if mruiter is willing to do some work on it. Never the less, i'll donate a little ;-)

**Comment by mhoogenbosch** [comment]
Don't know what exactly @mruiter needs to support this, but i'll post some info, it's from the developer page.

Key | Value
-- | --
zw_node_id | "15"
zw_manufacturer_id | "340"
zw_product_type_id | "3"
zw_product_id | "10"
zw_secure | "⨯"
zw_battery | "⨯"
zw_device_class_basic | "BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic | "GENERIC_TYPE_SWITCH_BINARY"
zw_device_class_specific | "SPECIFIC_TYPE_POWER_SWITCH_BINARY"
zw_firmware_id | "778"

**Comment by mhoogenbosch** [comment]
Installed the beta. Took a while for the Generic Zwave device to be removed, but that worked. I could add it as a 'smart outdoor plug', but after adding the pop application crashes. The device has an ID on the zwave page on developer. Let me know if i can do something to help you out.

Let's go with the other topic and close this one. 

See: https://github.com/mruiter/com.popp/issues/36

**Comment by mhoogenbosch** [comment]
Beta works

**Comment by mruiter** [comment]
Solved in latest versions
