### ISSUE TITLE
Tested 009501 - Secure Flow Stop – Valve Shut-Off

### ISSUE THREAD

**Issue by pieterh99** [mruiter/com.popp#42]
I've tested the valve. When I try to add the valve the app always mention that it's ' already added'. But in my devices list there is no valve or any other device from the popp app. 

How can I help you to resolve this issue?

**Comment by mruiter** [comment]
Remove it from homey by going to settings zwave and remove device procedure . Guess the first pair went wrong. Then the device and the homey zwave chip are paired but the homey software doesn’t . Then you get the device already paired error 

Verstuurd vanaf mijn iPhone

**Comment by pieterh99** [comment]
Thanks for the fast response. I've tried to remove the valve. The result is that i've now a non-popp valve in my devices list and functioning as expected. I think that the same valve is also branded under different brands.
