### ISSUE TITLE
Smoke Alarm app. Confused

### ISSUE THREAD

**Issue by ks2018ks** [mruiter/com.popp#43]
Hi I've got a few Smoke Alarm and sirens, powered with mains adapter. (It seems I must also have batteries installed as a backup, but in fact the batteries seem to drain fast anyway). Nevertheless I am confused with what is going on with the app. As can be seen in the screenshot below, in some of the devices the icons are white, some grey, some grey with an exclamation mark. It's not clear to me what is meant by each. If I press and hold the white one, I get an icon of a power button illuminated green. What does that mean? Does it mean the siren is supposed to be sounding or simply that the device is enabled? If I do the same for a grey icon the alarm siren starts, and won't go off until I turn it off again. 

![Screenshot_20190421-175657](https://user-images.githubusercontent.com/37977911/56473193-6e7f0680-645f-11e9-87e0-6b5a62f57693.png)

**Comment by mapulu** [comment]
White is on, grey is off. It should be for the siren. Also the On-Off in the Device.
The exclamation mark shows there is an alarm, (smoke/tamper/battery alarm)
