### ISSUE TITLE
Z-Rain does not work at all

### ISSUE THREAD

**Issue by osochor** [mruiter/com.popp#44]
No measured values are transferred to homey.
Homey v2.1.1
Popp App 2.0.6 beta

**Comment by Tigerliljan** [comment]
Same for me :(
Homey v2.1.2
Popp app v2.0.6 beta

**Comment by HenricAsk** [comment]
Same for me, no values reported to Homey
Homey V2.4.1
Popp App V2.0.6 beta

Can you please fix this. Would be much appreciated.

**Comment by HenricAsk** [comment]
Z-rain now works :)
Homey V2.5.0
Popp App V2.0.10

Thanks for great work :)

**Comment by mruiter** [comment]
Confirmed working in latest versions of app
