### ISSUE TITLE
[Request] Support for Popp Popp Door and Window Sensor with Tilt Detection

### ISSUE THREAD

**Issue by osochor** [mruiter/com.popp#45]
Any chance support can be added for Popp Door and Window Sensor with Tilt Detection please?

(Product Code: 700892) 
http://manuals-backend.z-wave.info/make.php?lang=en&sku=POPE700892&cert=

**Comment by markhaehnel** [comment]
I would love to get support for this device. I can help with testing and debugging this. Already have one at home.

**Comment by markhaehnel** [comment]
This get's implemented in PR #50.

**Comment by mruiter** [comment]
Its pending approval in the appstore since yesterday , Thx Mark btw .

**Comment by mruiter** [comment]
Confirmed working in latest versions of app
