### ISSUE TITLE
Popp app

### ISSUE THREAD

**Issue by Hans1965** [mruiter/com.popp#48]
Marco, de Popp app kan ik niet installeren, andere apps wel.
ik gebruik Homey v2.1.2
Popp App 2.0.6 beta of de Stable version 1.17 won’t install on my homey.

**Comment by sssmsb** [comment]
I have the same problem. Both with beta and non beta version.

The message is: "Nnn's Homey Pro is unreachable. Try again."

**Comment by mruiter** [comment]
Confirmed working in latest versions of app

**Comment by Hans1965** [comment]
Dankjewel Marco,

Ik ga hem dit weekend uitproberen!

Met vriendelijke groet,

Hans Luijk
