### ISSUE TITLE
PoPP Eu Z-Wave wireless Thermo won't install on Homey 2

### ISSUE THREAD

**Issue by ruudvanz** [mruiter/com.popp#49]
PoPP Eu Z-Wave wireless Thermo Valve won't install on Homey Pro 2.3.0
https://apps.athom.com shows Popp is still available for install, despite being installed.
On the IOS App installation of the Valve (after a serach for Popp) fails after a few seconds waiting on "green installing bar" then fails with a "red top bar"message App could not be installed
![IMG_1844](https://user-images.githubusercontent.com/22626006/61295199-cd8eb600-a7d7-11e9-985b-65b6525cbdc5.PNG)

**Comment by mruiter** [comment]
There should be an new beta update any day now . Its pending approval in the appstore since yesterday ,
