### ISSUE TITLE
Popp Z-Weather

### ISSUE THREAD

**Issue by Bhitv** [mruiter/com.popp#5]
Hello Marco
I would like to get my Z-Weather working.
I have permission to return him later.
Have now discovered how to send you a log.
Hereby, I hope you can do something about it here.
Thank you for your effort.

Mvg Bernard Huisintveld

5-7-2017 14:40:23.997	Zwave	Log	Node[14] (Z-Weather): Received application command for COMMAND_CLASS_BATTERY, data: 0x0364
5-7-2017 14:40:23.934	Zwave	Log	Command[4196] end: sendData
5-7-2017 14:40:23.888	Zwave	Log	ProcessSendData[4197]: To node: 14 with data: 0x8002 and txOptions: ACK,AUTO_ROUTE,EXPLORE
5-7-2017 14:40:23.883	Zwave	Log	Command[4196] start: sendData
5-7-2017 14:40:23.880	Zwave	Log	Node[14] (Z-Weather): sendData to COMMAND_CLASS_BATTERY, params 0x02
5-7-2017 14:40:23.782	Zwave	Log	Node[14] (Z-Weather): Marked as online
5-7-2017 14:40:23.762	Zwave	Log	Node[14] (Z-Weather): Received application command for COMMAND_CLASS_WAKE_UP, data: 0x07
5-7-2017 14:40:23.747	Zwave	Log	Node[14] (Z-Weather): Received application command for COMMAND_CLASS_BATTERY, data: 0x0364
5-7-2017 14:40:23.731	Zwave	Log	Node[14] (Z-Weather): Received application command for COMMAND_CLASS_METER, data: 0x0241a40003bc38010c0003bab1
5-7-2017 14:40:23.705	Zwave	Log	Node[14] (Z-Weather): Received application command for COMMAND_CLASS_METER, data: 0x02411c00001eca010c00001eca
5-7-2017 14:40:23.669	Zwave	Log	Node[14] (Z-Weather): Received application command for COMMAND_CLASS_SENSOR_MULTILEVEL, data: 0x050b220083
5-7-2017 14:40:23.652	Zwave	Log	Node[14] (Z-Weather): Received application command for COMMAND_CLASS_SENSOR_MULTILEVEL, data: 0x05092203f5
5-7-2017 14:40:23.555	Zwave	Log	Node[14] (Z-Weather): Received application command for COMMAND_CLASS_SENSOR_MULTILEVEL, data: 0x050501232e
5-7-2017 14:40:23.538	Zwave	Log	Node[14] (Z-Weather): Received application command for COMMAND_CLASS_SENSOR_MULTILEVEL, data: 0x05030164
5-7-2017 14:40:23.522	Zwave	Log	Node[14] (Z-Weather): Received application command for COMMAND_CLASS_SENSOR_MULTILEVEL, data: 0x050122012e
5-7-2017 14:40:23.513	Zwave	Log	Node[14] (Z-Weather): Received application command for COMMAND_CLASS_SENSOR_MULTILEVEL, data: 0x05060100
5-7-2017 14:40:24.007	Zwave	State	{"zw_state":{"stats":{"processmanager":{"processQueue":0}},"ver":5,"capabilities":{"api":"controller","timerSupported":false,"controllerType":"primary"},"nodes":[1,2,3,4,5,7,8,11,14],"chip_type":5,"chip_version":0,"homeId":4081622581,"nodeId":1,"nvr":[1,4,0,21,13,27,120,32,1,0,32,0,64,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,23,19,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,116,244],"CONTROLLER_IS_SECONDARY":false,"CONTROLLER_ON_OTHER_NETWORK":false,"CONTROLLER_NODEID_SERVER_PRESENT":true,"CONTROLLER_IS_REAL_PRIMARY":true,"CONTROLLER_IS_SUC":true,"NO_NODES_INCUDED":false,"sucId":1,"powerLevel":0,"version":"Z-Wave 3.99","networkKey":"a6d2792277751c7828807b3b52a4a29f","methodsAsync":["factoryReset","addNodeAbort","removeNodeAbort","replaceFailedNodeAbort","sendData","isFailedNode","getFailedNodes","ping"]},"zw_ready":true,"_stateTimestamp":1499258424018}
5-7-2017 14:40:23.943	Zwave	State	{"zw_state":{"stats":{"processmanager":{"processQueue":0}},"ver":5,"capabilities":{"api":"controller","timerSupported":false,"controllerType":"primary"},"nodes":[1,2,3,4,5,7,8,11,14],"chip_type":5,"chip_version":0,"homeId":4081622581,"nodeId":1,"nvr":[1,4,0,21,13,27,120,32,1,0,32,0,64,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,23,19,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,116,244],"CONTROLLER_IS_SECONDARY":false,"CONTROLLER_ON_OTHER_NETWORK":false,"CONTROLLER_NODEID_SERVER_PRESENT":true,"CONTROLLER_IS_REAL_PRIMARY":true,"CONTROLLER_IS_SUC":true,"NO_NODES_INCUDED":false,"sucId":1,"powerLevel":0,"version":"Z-Wave 3.99","networkKey":"a6d2792277751c7828807b3b52a4a29f","methodsAsync":["factoryReset","addNodeAbort","removeNodeAbort","replaceFailedNodeAbort","sendData","isFailedNode","getFailedNodes","ping"]},"zw_ready":true,"_stateTimestamp":1499258423957}
5-7-2017 14:40:23.929	Zwave	State	{"zw_state":{"currentProcess":"ProcessSendData","stats":{"processmanager":{"processQueue":0}},"ver":5,"capabilities":{"api":"controller","timerSupported":false,"controllerType":"primary"},"nodes":[1,2,3,4,5,7,8,11,14],"chip_type":5,"chip_version":0,"homeId":4081622581,"nodeId":1,"nvr":[1,4,0,21,13,27,120,32,1,0,32,0,64,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,23,19,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,116,244],"CONTROLLER_IS_SECONDARY":false,"CONTROLLER_ON_OTHER_NETWORK":false,"CONTROLLER_NODEID_SERVER_PRESENT":true,"CONTROLLER_IS_REAL_PRIMARY":true,"CONTROLLER_IS_SUC":true,"NO_NODES_INCUDED":false,"sucId":1,"powerLevel":0,"version":"Z-Wave 3.99","networkKey":"a6d2792277751c7828807b3b52a4a29f","methodsAsync":["factoryReset","addNodeAbort","removeNodeAbort","replaceFailedNodeAbort","sendData","isFailedNode","getFailedNodes","ping"],"currentCommand":"sendData"},"zw_ready":true,"_stateTimestamp":1499258423915}
5-7-2017 14:40:23.810	Zwave	State	{"zw_state":{"stats":{"processmanager":{"processQueue":0}},"ver":5,"capabilities":{"api":"controller","timerSupported":false,"controllerType":"primary"},"nodes":[1,2,3,4,5,7,8,11,14],"chip_type":5,"chip_version":0,"homeId":4081622581,"nodeId":1,"nvr":[1,4,0,21,13,27,120,32,1,0,32,0,64,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,23,19,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,116,244],"CONTROLLER_IS_SECONDARY":false,"CONTROLLER_ON_OTHER_NETWORK":false,"CONTROLLER_NODEID_SERVER_PRESENT":true,"CONTROLLER_IS_REAL_PRIMARY":true,"CONTROLLER_IS_SUC":true,"NO_NODES_INCUDED":false,"sucId":1,"powerLevel":0,"version":"Z-Wave 3.99","networkKey":"a6d2792277751c7828807b3b52a4a29f","methodsAsync":["factoryReset","addNodeAbort","removeNodeAbort","replaceFailedNodeAbort","sendData","isFailedNode","getFailedNodes","ping"]},"zw_ready":true,"_stateTimestamp":1499258423793}
5-7-2017 14:40:23.591	Z-Weather	Measure_humidity	35
5-7-2017 14:40:23.576	Z-Weather	Measure_temperature	30.2

**Comment by Bhitv** [comment]
Let me know if I'm wrong.
I have learned a lot lately, but do not know if it's all the right way.

**Comment by Bhitv** [comment]
Hallo Marco 
Helaas, geen reactie meer van jou, ik heb geen andere keuze dan mijn z-weather terug te sturen. 
Op een of andere manier kun of wil je niet verder met me, als ik het verkeerd doe of gedaan heb, sorry!! 
Ik had gehoopt om er samen uit te komen. 
Had speciaal hiervoor uitstel gekregen van het retour termijn. 
Maar ja kan hem niet altijd houden. 
Ik had deze issue geplaatst in de hoop dat je er iets mee kon, maar helaas niet een reactie. 
'T is niet anders, ik stuur hem dinsdag retour.

**Comment by mruiter** [comment]
Ik ben redelijk afwezig momenteel. Maar je log laat geen enkel report zien van wind.
Vrees dat het erg lastig wordt het snel in orde te maken.
Mogelijk dat iemand een z-weather koopt met z-wave kennis of hem uitleent zodat ik de wind in orde kan maken.

**Comment by Bhitv** [comment]
Oke, dank je voor je reactie
Jammer maar het is niet anders
Ik ga hem vandaag retour sturen, zal het bedrijf doorgeven dat het niet lukt.
Ik wacht rustig af tot er een vergelijkend z-wave apparaat op de markt komt.

Iig bedankt voor je inzet, en succes met je andere projecten.
