### ISSUE TITLE
Popp flow valve not been added. 

### ISSUE THREAD

**Issue by toyskung** [mruiter/com.popp#51]
Cannot add popp flow valve. Is there a fix to add it even if it has the wrong device Code?
![1EC99DC7-50BC-4F0F-8548-86BF3EDA0C2E](https://user-images.githubusercontent.com/53265783/61798589-d449a880-ae29-11e9-8265-012b8f866e95.png)

**Comment by mapulu** [comment]
Did you try the beta app? The product id is not in the stable app version but in the beta app.

**Comment by toyskung** [comment]
Hi. I have tryed several times with the beta app without been able to add it. Every time it fails.

**Comment by mapulu** [comment]
Sorry seems that I was wrong.

It will take some time for the next PR.
I added the IDs to my fork, you could CLI install that. 

https://github.com/mapulu/com.popp/tree/beta
https://community.athom.com/t/how-to-cli-install-method/198

**Comment by Wanegn** [comment]
I have the same issue. On the releast version dated 30.july 2019

**Comment by Wanegn** [comment]
@mapulu Will it be an official release of v 2.0.12 to the app store ? I  see that this contain both valve and smart outdoor plug.

**Comment by mapulu** [comment]
Its released as beta
