### ISSUE TITLE
Can't add Power Plug 700793

### ISSUE THREAD

**Issue by Milleniumfalke** [mruiter/com.popp#57]
When I add the device the message appears: waiting for device
after several seconds message appears: No z-wave device found.
if I try a second time message appears: status.already_added
next step  Setup  - z-wave - Remove a device - then I can start again but the same result - can't find device

**Comment by mruiter** [comment]
If it’s the k my device doing this it’s a faulty devices . Else check you’re zwave logs because this is not a app error but a zwave error or homey core . Also remove power from homey to give the zwave chip a clean start


Verstuurd vanaf mijn iPhone

**Comment by Milleniumfalke** [comment]
Hi Marco,


thank you for your answer. I'll try some things.


What di you mean with: If it’s the k my device doing this...


Regards Franz









L.G.Franz




Franz Strohmaier


Lemsitz 89 


A-8511 St. Stefan


Tel.: +43 ; 664 2239875


Fax: +43 (0) 3463 81289


e-Mail: franz.strohmaier@physio-strohmaier.at 







On Tue, Sep 24, 2019 at 8:03 PM +0200, "Marco Ruiter" <notifications@github.com> wrote:










If it’s the k my device doing this it’s a faulty devices . Else check you’re zwave logs because this is not a app error but a zwave error or homey core . Also remove power from homey to give the zwave chip a clean start








Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Hello Frans

Sorry that was some spellcheck correction I guess

It should be saying that if this is the only device doing this it could be a faulty device 

Verstuurd vanaf mijn iPhone

> Op 26 sep. 2019 om 19:56 heeft Milleniumfalke <notifications@github.com> het volgende geschreven:
> 
> ﻿Hi Marco,
> 
> 
> thank you for your answer. I'll try some things.
> 
> 
> What di you mean with: If it’s the k my device doing this...
> 
> 
> Regards Franz
> 
> 
> 
> 
> 
> 
> 
> 
> 
> L.G.Franz
> 
> 
> 
> 
> Franz Strohmaier
> 
> 
> Lemsitz 89 
> 
> 
> A-8511 St. Stefan
> 
> 
> Tel.: +43 ; 664 2239875
> 
> 
> Fax: +43 (0) 3463 81289
> 
> 
> e-Mail: franz.strohmaier@physio-strohmaier.at 
> 
> 
> 
> 
> 
> 
>

**Comment by Milleniumfalke** [comment]
Hi Marco,

I tried another device – that worked perfectly. Thanks for your suppert

 

BR.Franz
 



 

Von: Marco Ruiter <notifications@github.com> 
Gesendet: Donnerstag, 26. September 2019 20:19
An: mruiter/com.popp <com.popp@noreply.github.com>
Cc: Milleniumfalke <franz.strohmaier@physio-strohmaier.at>; Author <author@noreply.github.com>
Betreff: Re: [mruiter/com.popp] Can't add Power Plug 700793 (#57)

 

Hello Frans

Sorry that was some spellcheck correction I guess

It should be saying that if this is the only device doing this it could be a faulty device 

Verstuurd vanaf mijn iPhone

> Op 26 sep. 2019 om 19:56 heeft Milleniumfalke <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:
> 
> ﻿Hi Marco,
> 
> 
> thank you for your answer. I'll try some things.
> 
> 
> What di you mean with: If it’s the k my device doing this...
> 
> 
> Regards Franz
> 
> 
> 
> 
> 
> 
> 
> 
> 
> L.G.Franz
> 
> 
> 
> 
> Franz Strohmaier
> 
> 
> Lemsitz 89 
> 
> 
> A-8511 St. Stefan
> 
> 
> Tel.: +43 ; 664 2239875
> 
> 
> Fax: +43 (0) 3463 81289
> 
> 
> e-Mail: franz.strohmaier@physio-strohmaier.at <mailto:franz.strohmaier@physio-strohmaier.at>  
> 
> 
> 
> 
> 
> 
>

**Comment by mruiter** [comment]
You’re welcome
