### ISSUE TITLE
Receive message 'Er is geen geschikt Homey App gevonden voor dit apparaat...'

### ISSUE THREAD

**Issue by jstelten** [mruiter/com.popp#6]
Receive message 'Er is geen geschikt Homey App gevonden voor dit apparaat...'

' Er is geen geschikt Homey App gevonden voor dit apparaat. Het apparaat is toegevoegd als Basic-Z-Wate Apparaat'.

Below the device info:

Device: Popp IP20

Fabrikant ID: 340
Product Type ID: 3
Product ID: 1

Version installed: v1.1.5

**Comment by mruiter** [comment]
Could you please try with my latest github version 1.6?
It has the id's added of youre plug

**Comment by jstelten** [comment]
Work like a charm, thanks!
