### ISSUE TITLE
Battery alarm/info is not reset

### ISSUE THREAD

**Issue by rindlerblabla** [mruiter/com.popp#63]
As mentioned in #27 the battery info is not updated for the 004001 smoke sensor after triggered low battery alarm. The low battery alarm is it self triggering the smoke alarm, I think.

Have now changed to new battery in a smoke sensor but is still showing that exclamation mark on the device, and says 1% battery level when swiping to battery info.

**Comment by satbopper** [comment]
i had the same issue,what i did is change the battery,removed the device from homey
installed the default popp app,added the sirene device,for me it showed the full battery,then i installed the beta popp app and back to business

**Comment by rindlerblabla** [comment]
With a maintenance option like this it would be possible to reset the alarm. https://github.com/Thorarin/com.sensative/commit/0dbeb1bf0b05072d019e17f24de9274be562547e

**Comment by mruiter** [comment]
@rindlerblabla the way Athom has fixed their zwave core bug is wrong.
A) they should just fix the zwave core . S2 security and FLIRS
B) The workaround implementation directly on the device control is wrong. This gives connected systems wrong info on the devices. Like thermo sensors and other devices classes will be seen as switches . Athom should implement this option in the advanced devices settings.

**Comment by mruiter** [comment]
Should have improved big time with the release of V7 firmware.
