### ISSUE TITLE
Strike Lock Control = Secure Flow Stop – Valve Shut-Off

### ISSUE THREAD

**Issue by twellocity** [mruiter/com.popp#7]
Hello , i had a working strike lock control, and a bought another one. when including is was including as Secure Flow Stop – Valve Shut-Off.! (whitch gives and error)
for testing i excluded my first strike lock control. and this one when including it showed up as Secure Flow Stop – Valve Shut-Off either!
Can you please help me and look into this problem?

**Comment by mruiter** [comment]
MMMm. I see the problem.  In the PoPP documentation both devices have the same ProductID's

I Guess the one in the valve mentioned it wrong because you already confirmed it as working.

I will update it in a few minutes.
The new version will be on github. Ill put another message here when its on there

**Comment by mruiter** [comment]
Its uploaded please try this version when installing by Athom Cli

**Comment by twellocity** [comment]
Hello, today i downloaded the 1.16 version and did a node.js install (first time i did this :-)
Succeeded, its working ! I have now two strike lock controls working. thanks a lot for fixing this . (very quickly too)

**Comment by mruiter** [comment]
Doing the best i can with the little time i have.


Enjoying your thx 




Outlook voor Android downloaden







On Tue, Jul 18, 2017 at 9:21 PM +0200, "twellocity" <notifications@github.com> wrote:












Hello, today i downloaded the 1.16 version and did a node.js install (first time i did this :-)

Succeeded, its working ! I have now two strike lock controls working. thanks a lot for fixing this . (very quickly too)
