### ISSUE TITLE
Tamper alarm of 10 year smoke detector and siren (009402) does not work

### ISSUE THREAD

**Issue by JosStultjens** [mruiter/com.popp#74]
The tamper alarm of the 10 year smoke detector and siren does not work.
FYI: The tamper alarm of the CO sensor does work.

I am using Popp app version v2.0.12

My device id and other info is:
zw_manufacturer_id | "340"
zw_product_type_id | "4"
zw_product_id | "4"
zw_secure | "✓"
zw_battery | "⨯"
zw_device_class_basic | "BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic | "GENERIC_TYPE_SENSOR_NOTIFICATION"
zw_device_class_specific | "SPECIFIC_TYPE_NOTIFICATION_SENSOR"
zw_firmware_id | "271"
zw_application_version | "1"
zw_application_sub_version | "15"
zw_hardware_version | "1"

**Comment by mruiter** [comment]
Fixed in latest version 2.1.1
