### ISSUE TITLE
Smoke alarm of 10 years smoke detector and siren does not trigger flow ( 009402 )

### ISSUE THREAD

**Issue by JosStultjens** [mruiter/com.popp#75]
I have 4 Popp 009402 10 Year smoke detectors and siren.
I do not have a test smoke can so I cannot test the smoke alarm myself, but Martijn Chel does and he found out that the alarm on the sensor itself sounds the alarm but no flow is being triggered when he tests with a test smoke can.

Please check also his message in the community messageboard: https://community.athom.com/t/problems-popp-004001-smoke-detector-and-siren/7249/19

**Comment by mruiter** [comment]
Should be fixed in latest 2.1.1 version
