### ISSUE TITLE
Is CO sensor (004407) able to report temperature?

### ISSUE THREAD

**Issue by JosStultjens** [mruiter/com.popp#76]
Is CO sensor (004407) able to report temperature? 
I was not able to find any such capability in the Popp documentation. 
If it actually can't report temperature, please remove it from the Homey app device page to avoid confusion.
If it can report temperature, then please make it work.

**Comment by mruiter** [comment]
Users reported in the past that where some modules that could and some that could not.
There was no difference in device id so its added for the revisions that do support it.
