### ISSUE TITLE
Tamper-Alarm at sensors without any reason

### ISSUE THREAD

**Issue by dirkg173** [mruiter/com.popp#80]
Hello @mruiter,
since Athom released the Homey firmware version 5.0 Beta, tamper alarms have been activated on various Z-Wave sensors from different manufacturers (in mine case Fibaro, Aeotec, POPP, Sensative) for no reason. If you deactivate the tamper alarms by waking up the sensor, the tamper alarm will activate within the next few hours up to 2-3 days without any reason.
Athom seems to have solved this problem with their Fibaro App. Since 9 days the tamper alarm has not been activated on door/window sensors, motion sensors and water sensors.
However, the problem still occurs on my door/window sensor from POPP.

For this reason I kindly ask you to contact Athom regarding the problem with the tamper alarms and fix the error in the POPP app.
I am currently also in contact with Aeotec in this regard.

By the way, I have a window sensor and 3 motion sensors from NEO Coolcam where the problem hasn't shown up yet.

Kind regards,
Dirk

**Comment by mruiter** [comment]
No need to contact athom . As soon as time comes by there will be a app update 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
The neo app already got the update . Aeotec Will also be updated when athom has time for it . 

It’s a bug introduced in homey v5 and needs manual fixing in the app

Verstuurd vanaf mijn iPhone

**Comment by dirkg173** [comment]
Many thanks for the information.
The Aeotec App is now officially maintained by Aeotec (see App Store). Therefore I have contacted Aeotec directly. Athom didn't want to have anything more to do with the Aeotec App 1-2 months ago. ;)
