### ISSUE TITLE
Strike lock

### ISSUE THREAD

**Issue by Grasduyn** [mruiter/com.popp#85]
We moeten de strike lock controls telkens opnieuw installeren. Dan werken ze weer een dag, maar dan stopt het weer. Wat doen we fout? De code is: 26f0141c-c94e-4eaa-8ae2-383bc90b87aa

**Comment by mruiter** [comment]
Hier is niets aan te vinden. Ik vrees dat het bereik te slecht is . Homey heeft een probleem met het FLiRS protocol dat deze strike lock kan gebruiken. AThom is momenteel bezig met de implementatie ervan.

Een gekke tussen oplossing die vaak lijkt te werken is , de Fibaro app te installeren. (de laatste test versie)
Dan tijdens het pairen van de strike lock te kiezen voor fibaro en dan walli schakelaar.

Dan wordt het device geforeceerd zonder de flirs en de niet functionerende security toegevoegd.
