### ISSUE TITLE
Problem with Popp wireless thermo Valve

### ISSUE THREAD

**Issue by Patronick3** [mruiter/com.popp#86]
Hello
firstly let me say thank you for this great app. Unfortunately I am facing a issue with popp thermo valves. When the target temperature is set to 20 degrees and  I set new target temperature to 22 degreees this change shows imediately in the device list and also in the device details. After wake up interval (in my case 600 sconds) this new value 22 degrees are sent to valves but in the device list and device details it changes back to the previous value 20 degrees. After another 600 sconds this value changes to the new value 22 degrees eventhought the Valve has new value after the first wake up interval. Could you please help me fix this issue? It is very problematic behaviour because my heating program is not working due this issue properly and turns on/ turns off eventhought the Valve has the right new value... many thank you and wish you a beautiful day.

**Comment by mruiter** [comment]
This means that the device did not report back on zwave that the temperature is changed.
This is a zwave issue. Nevertheless Athom has released v7 of the firmware. This should improve the issue you are seeen
