### ISSUE TITLE
No reading on Homey

### ISSUE THREAD

**Issue by lommers1965** [mruiter/com.popp#87]
Hi, 
can you help me out. I could pair the Z-Weather with my Homey Pro after I held it within a 20 cm distance. I installed the Z-weather on my terrace (about 15 meters away from Homey) and don't not get any readings at all. What am I doing wrong?
<img width="596" alt="Screenshot 2021-04-26 at 11 58 16" src="https://user-images.githubusercontent.com/78645262/116064996-d4be4580-a686-11eb-96e0-d6af8f1f2058.png">

**Comment by mruiter** [comment]
The zweather doesnt have a real battery but a  solar filled capacitor as far as i know.
Be sure its fully charged . If pairing then still fails its probably the device.
You could do a factory reset , the procedure should be in the device manual
