### ISSUE TITLE
Popp Power Plug

### ISSUE THREAD

**Issue by SvS1986** [mruiter/com.popp#89]
Hello,

I got 2 Popp Power plugs, but they won't connect with Home.
The 2 green check marks do it, but after the loading he says try later.

**Comment by mruiter** [comment]
Sound like a z-wave network issue and not a app problem. 
See the zwave log of youre homey whats causing it. I guess timeout of the device.
If so please refer to the community forums for seeking help on how to create a good working zwave network

**Comment by SvS1986** [comment]
Ik zie dat je Nederlands bent, dat praat wat makkelijker, als hij gaat laden na de groene vinkjes duurt het best lang, en erna zegt hij probeer het later nog een keer..

Zelfs naast de homey proberen te koppelen,
App opnieuw opnieuw geïnstalleerd, ptp, zwave geresett

**Comment by SvS1986** [comment]
6.1.0

**Comment by mruiter** [comment]
There will be a new version of homey firmware available anytime in experimental (read within days)
It holds a lot of zwave improvements and solves a lot of bugs in the interviews during pair.
I hope this will solve youre problem.
Also its advised to do a factory reset of the device and not just a unpair and re-pair. A factory default reset procedure should be in the manual
