### ISSUE TITLE
Secure Flow Stop - Valve

### ISSUE THREAD

**Issue by juuldk** [mruiter/com.popp#9]
Today I managed to get some time to play with my Homey and the Secure Flow Stop - Valve.
I have now side loaded the latest version, and it did detect the Valve ok.
The settings also looked fine, but when trying to look at the values, it failed.
I have attached 2 screen shots. Hopefully this will help you find the issue.

Thanks,
Jan
<img width="988" alt="screen shot 2017-11-04 at 15 20 54" src="https://user-images.githubusercontent.com/33067163/32406282-009655ca-c176-11e7-8553-e267366c2242.png">
<img width="930" alt="screen shot 2017-11-04 at 15 21 23" src="https://user-images.githubusercontent.com/33067163/32406300-552220c4-c176-11e7-9a5c-62d6dbfa1045.png">

**Comment by mruiter** [comment]
I have a SDKv2 version of the PoPP app on my github.
This should be fixed in the latest.
