### ISSUE TITLE
Problem with including 700397

### ISSUE THREAD

**Issue by AxelF70** [mruiter/com.popp#90]
I have problems to include 700397 into my system. Tried various things like: different locations compared to Homey, add as Outdoor wall switch. At the end I did got it included (5 cm from the homey) but the plug was unresponsive to my actions.
I have a hard time to understand the root cause of this and hope that someone here recognize the problem.
Using an Homey Pro 6.1.0 (early 2019) and version 2.0.12 of the app PoPP EU Z-Wave Products.

**Comment by mruiter** [comment]
There will be a new version of homey firmware available anytime in experimental (read within days)
It holds a lot of zwave improvements and solves a lot of bugs in the interviews during pair.
I hope this will solve youre problem.
Also its advised to do a factory reset of the device and not just a unpair and re-pair. A factory default reset procedure should be in the manual
