### ISSUE TITLE
Battery level very different from level reported by Homey 

### ISSUE THREAD

**Issue by ks2018ks** [mruiter/com.popp#91]
Hi,

I have a homey flow to let me know when a device battery is low and might need changing:
![image](https://user-images.githubusercontent.com/37977911/120662398-0645e000-c481-11eb-8430-2d90cecb116e.png)

I often get a warning like this from the Popp Radiator:
![image](https://user-images.githubusercontent.com/37977911/120662493-1cec3700-c481-11eb-8f6d-7330380b0a20.png)

...but the Homey system shows a completely different value: 67% not 3%:

![image](https://user-images.githubusercontent.com/37977911/120662571-2aa1bc80-c481-11eb-9a5a-3739015a0ea7.png)

**Comment by mruiter** [comment]
Battery reporting is completely done by homey core. Nothing i can do about this . Only athom could by improving z-wave in homey core.
Nevertheless. All z-wave platforms have issues in all ranges with the battery class and getting the values correctly

**Comment by ks2018ks** [comment]
Hello Marco - how is it that what is reported by your app (3%) is so different than what is reported elsewhere by the Homey app (67%)?
