### ISSUE TITLE
Popp sirene

### ISSUE THREAD

**Issue by eeckelaertyannick** [mruiter/com.popp#92]
Hi Marco,

I just received my popp sirene. But enclusion not possible. Even after resetting the device. I have a working zwave network with fibaro en neo coolcam devices. If I exclude the device it gives tot green labels but he stops en gives an error that says it dit not work. Can you advice?

**Comment by eeckelaertyannick** [comment]
Solved the problem. Deleted 2 unknown device's en it worked.

**Comment by eeckelaertyannick** [comment]
Stil one question.
Temp is not showing. Is this normal?

**Comment by mruiter** [comment]
Temperature has been removed in the V2 version of the device by PoPP.
The news test version of the app also has it removed. So it will soon dissapear.

**Comment by eeckelaertyannick** [comment]
Ok thx!



Met vriendelijke groet,

Yannick Eeckelaert
